api:
  id: "" 

app:
  name:  "sales order fulfillment" 
  version: ""  
  env: ""

salesforce:
  userName: "mulesoftintegration@ntnusa.com"
  consumerkey: "3MVG9zlTNB8o8BA1T1gSt15tI0eCCfz2mZwvXlYeqAG5KoxwJdUTEkV3bZS9B5a4uMLPXa0f9WSU_7stONFky"

database:
  host: ""
  port: ""
  userName: ""
  serviceName: ""
